name: flutter_sample
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/ic_facebook.png
    - images/ic_google.png
    - images/product/1.jpg
    - images/product/2.jpg
    - images/product/3.jpg
    - images/product/4.jpg
    - images/product/5.jpg

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-ExtraBold.otf
        - asset: fonts/Gilroy-Light.otf

    - family: Nanum
      fonts:
        - asset: fonts/NanumSquareRoundEB.ttf
        - asset: fonts/NanumSquareRoundL.ttf
